name: imago
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  avatar_view: ^1.0.1
  camera_deep_ar: ^0.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_gradients: ^1.0.0+3
  flutter_image_compress: ^1.1.0
  image_cropper: ^1.4.1
  image_editor_pro: ^1.1.8
  image_gallery_saver: ^1.6.6
  image_picker: ^0.7.4
  permission_handler: ^7.0.0
  photofilters: ^3.0.1
  screenshot: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/memes/meme-1.jpg
    - assets/memes/meme-2.jpeg
    - assets/memes/meme-3.jpg
    - assets/memes/meme-4.jpg
    - assets/memes/meme-5.webp
    - assets/memes/meme-6.jpg
    - assets/memes/meme-7.jpg
    - assets/memes/meme-8.webp
    - assets/memes/meme-9.png
    - assets/memes/meme-10.jpg
    - assets/memes/meme-11.jpg
    - assets/memes/meme-12.png
    - assets/memes/meme-13.jpg
    - assets/memes/meme-14.jpg
    - assets/memes/meme-15.png
    - assets/memes/meme-16.jpg
    - assets/memes/meme-17.jpg
    - assets/memes/meme-18.jpg
    - assets/memes/meme-19.png
    - assets/memes/meme-20.jpg
    - assets/memes/meme-21.jpg
    - assets/memes/meme-22.png
    - assets/memes/meme-23.jpg
    - assets/memes/meme-24.png
    - assets/memes/meme-25.jpg
    - assets/memes/meme-26.jpg
    - assets/memes/meme-27.jpg
    - assets/memes/meme-28.jpg
    - assets/memes/meme-29.png
    - assets/memes/meme-30.jpg
    - assets/memes/meme-31.jpg
    - assets/memes/meme-32.jpg
    - assets/memes/meme-33.jpg
    - assets/memes/meme-34.png
    - assets/memes/meme-35.jpg
    - assets/memes/meme-36.jpg
    - assets/memes/meme-37.jpg
    - assets/memes/meme-38.jpg
    - assets/memes/meme-39.jpg
    - assets/memes/meme-40.jpg
    - assets/memes/meme-41.jpg
    - assets/memes/meme-42.jpg
    - assets/memes/meme-43.jpg
    - assets/memes/meme-44.jpg
    - assets/memes/meme-45.jpg
    - assets/memes/meme-46.jpg
    - assets/memes/meme-47.jpg
    - assets/memes/meme-48.png
    - assets/memes/meme-49.jpeg
    - assets/memes/meme-50.jpeg
    - assets/memes/meme-51.jpg
    - assets/memes/meme-53.png
    - assets/memes/meme-54.jpg
    - assets/filters/0.jpg
    - assets/filters/1.jpg
    - assets/filters/2.jpg
    - assets/filters/3.jpg
    - assets/filters/4.jpg
    - assets/filters/5.jpg
    - assets/filters/6.jpg
    - assets/filters/7.jpg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
